#!/usr/bin/env python3
"""
FUSION26 - export PyTorch TinyGNN weights to ../tiny_gnn_weights.h.

Usage:
    python3 export_weights.py tiny_gnn.pt
    python3 export_weights.py tiny_gnn.pt ../tiny_gnn_weights.h

Kept separate from training so a saved checkpoint can be re-exported
without retraining. Output shapes match ../tiny_gnn.h:
    W_IN[8][6] B_IN[8] W_SELF[8][8] W_NEIGHBOR[8][8]
    B_HIDDEN[8] W_OUT[5][8] B_OUT[5]
"""
import sys

import torch

HIDDEN = 8
INPUTS = 6
ACTIONS = 5


def _fmt(v):
    return f"{float(v):.6f}f"


def _matrix(name, arr):
    lines = [f"static const float {name}[{len(arr)}][{len(arr[0])}] = {{"]
    for row in arr:
        lines.append("    {" + ", ".join(_fmt(v) for v in row) + "},")
    lines.append("};")
    return "\n".join(lines)


def _vector(name, arr):
    return (f"static const float {name}[{len(arr)}] = {{"
            + ", ".join(_fmt(v) for v in arr) + "};")


def export_header(state, path="../tiny_gnn_weights.h"):
    sd = {k: v.detach().cpu().numpy() for k, v in state.items()}

    w_in = sd["input_layer.weight"]
    b_in = sd["input_layer.bias"]
    w_self = sd["self_layer.weight"]
    w_neigh = sd["neighbor_layer.weight"]
    b_hidden = sd["hidden_bias"]
    w_out = sd["output_layer.weight"]
    b_out = sd["output_layer.bias"]

    body = f"""/*
 * FUSION26 - embedded weights for the tiny message-passing GNN.
 *
 * AUTO-GENERATED by tools/export_weights.py from a trained checkpoint.
 * Do NOT hand-edit. Feature order:
 *     [relGoalX, relGoalY, battery, priority, congestion, status]
 * Action order: [up, down, left, right, wait]
 *
 * Re-generate with:  python3 train_gnn.py
 *                    python3 export_weights.py tiny_gnn.pt
 */
#pragma once

{_matrix("W_IN", w_in)}

{_vector("B_IN", b_in)}

{_matrix("W_SELF", w_self)}

{_matrix("W_NEIGHBOR", w_neigh)}

{_vector("B_HIDDEN", b_hidden)}

{_matrix("W_OUT", w_out)}

{_vector("B_OUT", b_out)}
"""

    with open(path, "w") as fh:
        fh.write(body)
    return path


def main():
    if len(sys.argv) < 2:
        print("usage: export_weights.py <checkpoint.pt> [out.h]")
        sys.exit(1)
    ckpt = sys.argv[1]
    out = sys.argv[2] if len(sys.argv) > 2 else "../tiny_gnn_weights.h"
    state = torch.load(ckpt, map_location="cpu")
    path = export_header(state, out)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
